---
title: Choisirunelicence.com
relative_permalinks: false
markdown: kramdown
url: "http://choisirunelicence.com"

collections:
  licences:
    output: true
    permalink: /licences/:path/

defaults:
  -
    scope:
      path: ""
      type: "licences"
    values:
      layout: licence
      featured: false
      "hide-from-license-list": false

exclude:
  - app.coffee
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests
  - assets/vendor/zeroclipboard/test

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
